version: "3.8"
services:
  fastify-prisma-boilerplate-container:
    image: mcr.microsoft.com/devcontainers/javascript-node
    volumes:
      - ..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity
  
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastify-prisma-boilerplate-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: